title: "Samantha Metevier"
description: "PhD Student - Research in Education and Migration"   # or write a short tagline instead

url: "https://samantha-metevier.github.io"
baseurl: ""
theme: minima

header_pages:
  - index.md
  - research.md
  - cv.md
